/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.hu.badge.service.model.impl;

import com.liferay.hu.badge.service.model.Badge;
import com.liferay.hu.badge.service.service.BadgeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Badge service. Represents a row in the &quot;BadgePortlet_Badge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadgeImpl}.
 * </p>
 *
 * @author Borkuti Peter
 * @see BadgeImpl
 * @see com.liferay.hu.badge.service.model.Badge
 * @generated
 */
public abstract class BadgeBaseImpl extends BadgeModelImpl implements Badge {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a badge model instance should use the {@link Badge} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BadgeLocalServiceUtil.addBadge(this);
		}
		else {
			BadgeLocalServiceUtil.updateBadge(this);
		}
	}
}