/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.borkutip.lfrnevnapp.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NameEntity service. Represents a row in the &quot;nevnapp_NameEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.borkutip.lfrnevnapp.data.model.impl.NameEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.borkutip.lfrnevnapp.data.model.impl.NameEntityImpl}.
 * </p>
 *
 * @author Péter Borkuti
 * @see NameEntity
 * @see hu.borkutip.lfrnevnapp.data.model.impl.NameEntityImpl
 * @see hu.borkutip.lfrnevnapp.data.model.impl.NameEntityModelImpl
 * @generated
 */
public interface NameEntityModel extends BaseModel<NameEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a name entity model instance should use the {@link NameEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this name entity.
	 *
	 * @return the primary key of this name entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this name entity.
	 *
	 * @param primaryKey the primary key of this name entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the name ID of this name entity.
	 *
	 * @return the name ID of this name entity
	 */
	public long getNameId();

	/**
	 * Sets the name ID of this name entity.
	 *
	 * @param nameId the name ID of this name entity
	 */
	public void setNameId(long nameId);

	/**
	 * Returns the name of this name entity.
	 *
	 * @return the name of this name entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this name entity.
	 *
	 * @param name the name of this name entity
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this name entity.
	 *
	 * @return the gender of this name entity
	 */
	public int getGender();

	/**
	 * Sets the gender of this name entity.
	 *
	 * @param gender the gender of this name entity
	 */
	public void setGender(int gender);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		hu.borkutip.lfrnevnapp.data.model.NameEntity nameEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.borkutip.lfrnevnapp.data.model.NameEntity> toCacheModel();

	@Override
	public hu.borkutip.lfrnevnapp.data.model.NameEntity toEscapedModel();

	@Override
	public hu.borkutip.lfrnevnapp.data.model.NameEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}