/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package test.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Legacydb service. Represents a row in the &quot;legacydb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link test.sb.model.impl.LegacydbModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link test.sb.model.impl.LegacydbImpl}.
 * </p>
 *
 * @author peter
 * @see Legacydb
 * @see test.sb.model.impl.LegacydbImpl
 * @see test.sb.model.impl.LegacydbModelImpl
 * @generated
 */
public interface LegacydbModel extends BaseModel<Legacydb> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacydb model instance should use the {@link Legacydb} interface instead.
	 */

	/**
	 * Returns the primary key of this legacydb.
	 *
	 * @return the primary key of this legacydb
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacydb.
	 *
	 * @param primaryKey the primary key of this legacydb
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the legacydbid of this legacydb.
	 *
	 * @return the legacydbid of this legacydb
	 */
	public long getLegacydbid();

	/**
	 * Sets the legacydbid of this legacydb.
	 *
	 * @param legacydbid the legacydbid of this legacydb
	 */
	public void setLegacydbid(long legacydbid);

	/**
	 * Returns the name of this legacydb.
	 *
	 * @return the name of this legacydb
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this legacydb.
	 *
	 * @param name the name of this legacydb
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(test.sb.model.Legacydb legacydb);

	@Override
	public int hashCode();

	@Override
	public CacheModel<test.sb.model.Legacydb> toCacheModel();

	@Override
	public test.sb.model.Legacydb toEscapedModel();

	@Override
	public test.sb.model.Legacydb toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}