/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.borkuti.peter.scriptpp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the History service. Represents a row in the &quot;scriptpp_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.borkuti.peter.scriptpp.service.model.impl.HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.borkuti.peter.scriptpp.service.model.impl.HistoryImpl}.
 * </p>
 *
 * @author Peter Borkuti
 * @see History
 * @see hu.borkuti.peter.scriptpp.service.model.impl.HistoryImpl
 * @see hu.borkuti.peter.scriptpp.service.model.impl.HistoryModelImpl
 * @generated
 */
public interface HistoryModel extends BaseModel<History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a history model instance should use the {@link History} interface instead.
	 */

	/**
	 * Returns the primary key of this history.
	 *
	 * @return the primary key of this history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this history.
	 *
	 * @param primaryKey the primary key of this history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the history ID of this history.
	 *
	 * @return the history ID of this history
	 */
	public long getHistoryId();

	/**
	 * Sets the history ID of this history.
	 *
	 * @param historyId the history ID of this history
	 */
	public void setHistoryId(long historyId);

	/**
	 * Returns the company ID of this history.
	 *
	 * @return the company ID of this history
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this history.
	 *
	 * @param companyId the company ID of this history
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this history.
	 *
	 * @return the group ID of this history
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this history.
	 *
	 * @param groupId the group ID of this history
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this history.
	 *
	 * @return the user ID of this history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this history.
	 *
	 * @param userId the user ID of this history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this history.
	 *
	 * @return the user uuid of this history
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this history.
	 *
	 * @param userUuid the user uuid of this history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this history.
	 *
	 * @return the create date of this history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this history.
	 *
	 * @param createDate the create date of this history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this history.
	 *
	 * @return the modified date of this history
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this history.
	 *
	 * @param modifiedDate the modified date of this history
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the line of this history.
	 *
	 * @return the line of this history
	 */
	@AutoEscape
	public String getLine();

	/**
	 * Sets the line of this history.
	 *
	 * @param line the line of this history
	 */
	public void setLine(String line);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		hu.borkuti.peter.scriptpp.service.model.History history);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.borkuti.peter.scriptpp.service.model.History> toCacheModel();

	@Override
	public hu.borkuti.peter.scriptpp.service.model.History toEscapedModel();

	@Override
	public hu.borkuti.peter.scriptpp.service.model.History toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}