/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.borkuti.peter.scriptpp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ScriptOptions service. Represents a row in the &quot;scriptpp_ScriptOptions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.borkuti.peter.scriptpp.service.model.impl.ScriptOptionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.borkuti.peter.scriptpp.service.model.impl.ScriptOptionsImpl}.
 * </p>
 *
 * @author Peter Borkuti
 * @see ScriptOptions
 * @see hu.borkuti.peter.scriptpp.service.model.impl.ScriptOptionsImpl
 * @see hu.borkuti.peter.scriptpp.service.model.impl.ScriptOptionsModelImpl
 * @generated
 */
public interface ScriptOptionsModel extends BaseModel<ScriptOptions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a script options model instance should use the {@link ScriptOptions} interface instead.
	 */

	/**
	 * Returns the primary key of this script options.
	 *
	 * @return the primary key of this script options
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this script options.
	 *
	 * @param primaryKey the primary key of this script options
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the script options ID of this script options.
	 *
	 * @return the script options ID of this script options
	 */
	public long getScriptOptionsId();

	/**
	 * Sets the script options ID of this script options.
	 *
	 * @param ScriptOptionsId the script options ID of this script options
	 */
	public void setScriptOptionsId(long ScriptOptionsId);

	/**
	 * Returns the company ID of this script options.
	 *
	 * @return the company ID of this script options
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this script options.
	 *
	 * @param companyId the company ID of this script options
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this script options.
	 *
	 * @return the group ID of this script options
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this script options.
	 *
	 * @param groupId the group ID of this script options
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this script options.
	 *
	 * @return the user ID of this script options
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this script options.
	 *
	 * @param userId the user ID of this script options
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this script options.
	 *
	 * @return the user uuid of this script options
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this script options.
	 *
	 * @param userUuid the user uuid of this script options
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this script options.
	 *
	 * @return the create date of this script options
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this script options.
	 *
	 * @param createDate the create date of this script options
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this script options.
	 *
	 * @return the modified date of this script options
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this script options.
	 *
	 * @param modifiedDate the modified date of this script options
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the script name of this script options.
	 *
	 * @return the script name of this script options
	 */
	@AutoEscape
	public String getScriptName();

	/**
	 * Sets the script name of this script options.
	 *
	 * @param scriptName the script name of this script options
	 */
	public void setScriptName(String scriptName);

	/**
	 * Returns the dependency list of this script options.
	 *
	 * @return the dependency list of this script options
	 */
	@AutoEscape
	public String getDependencyList();

	/**
	 * Sets the dependency list of this script options.
	 *
	 * @param dependencyList the dependency list of this script options
	 */
	public void setDependencyList(String dependencyList);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		hu.borkuti.peter.scriptpp.service.model.ScriptOptions scriptOptions);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.borkuti.peter.scriptpp.service.model.ScriptOptions> toCacheModel();

	@Override
	public hu.borkuti.peter.scriptpp.service.model.ScriptOptions toEscapedModel();

	@Override
	public hu.borkuti.peter.scriptpp.service.model.ScriptOptions toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}