/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package permission.servicebuider.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Firstnames service. Represents a row in the &quot;permissiontest_Firstnames&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link permission.servicebuider.model.impl.FirstnamesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link permission.servicebuider.model.impl.FirstnamesImpl}.
 * </p>
 *
 * @author peter
 * @see Firstnames
 * @see permission.servicebuider.model.impl.FirstnamesImpl
 * @see permission.servicebuider.model.impl.FirstnamesModelImpl
 * @generated
 */
public interface FirstnamesModel extends BaseModel<Firstnames> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a firstnames model instance should use the {@link Firstnames} interface instead.
	 */

	/**
	 * Returns the primary key of this firstnames.
	 *
	 * @return the primary key of this firstnames
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this firstnames.
	 *
	 * @param primaryKey the primary key of this firstnames
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the firstname ID of this firstnames.
	 *
	 * @return the firstname ID of this firstnames
	 */
	public long getFirstnameId();

	/**
	 * Sets the firstname ID of this firstnames.
	 *
	 * @param firstnameId the firstname ID of this firstnames
	 */
	public void setFirstnameId(long firstnameId);

	/**
	 * Returns the group ID of this firstnames.
	 *
	 * @return the group ID of this firstnames
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this firstnames.
	 *
	 * @param groupId the group ID of this firstnames
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this firstnames.
	 *
	 * @return the company ID of this firstnames
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this firstnames.
	 *
	 * @param companyId the company ID of this firstnames
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this firstnames.
	 *
	 * @return the user ID of this firstnames
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this firstnames.
	 *
	 * @param userId the user ID of this firstnames
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this firstnames.
	 *
	 * @return the user uuid of this firstnames
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this firstnames.
	 *
	 * @param userUuid the user uuid of this firstnames
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this firstnames.
	 *
	 * @return the create date of this firstnames
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this firstnames.
	 *
	 * @param createDate the create date of this firstnames
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this firstnames.
	 *
	 * @return the modified date of this firstnames
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this firstnames.
	 *
	 * @param modifiedDate the modified date of this firstnames
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the firstname of this firstnames.
	 *
	 * @return the firstname of this firstnames
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this firstnames.
	 *
	 * @param firstname the firstname of this firstnames
	 */
	public void setFirstname(String firstname);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(permission.servicebuider.model.Firstnames firstnames);

	@Override
	public int hashCode();

	@Override
	public CacheModel<permission.servicebuider.model.Firstnames> toCacheModel();

	@Override
	public permission.servicebuider.model.Firstnames toEscapedModel();

	@Override
	public permission.servicebuider.model.Firstnames toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}