/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.borkutip.lfrnevnapp.data.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import hu.borkutip.lfrnevnapp.data.model.NameEntity;
import hu.borkutip.lfrnevnapp.data.service.NameEntityLocalServiceUtil;

/**
 * The extended model base implementation for the NameEntity service. Represents a row in the &quot;nevnapp_NameEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NameEntityImpl}.
 * </p>
 *
 * @author Péter Borkuti
 * @see NameEntityImpl
 * @see hu.borkutip.lfrnevnapp.data.model.NameEntity
 * @generated
 */
public abstract class NameEntityBaseImpl extends NameEntityModelImpl
	implements NameEntity {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a name entity model instance should use the {@link NameEntity} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			NameEntityLocalServiceUtil.addNameEntity(this);
		}
		else {
			NameEntityLocalServiceUtil.updateNameEntity(this);
		}
	}
}