/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.borkuti.peter.scriptpp.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import hu.borkuti.peter.scriptpp.service.model.ScriptOptions;
import hu.borkuti.peter.scriptpp.service.model.ScriptOptionsModel;
import hu.borkuti.peter.scriptpp.service.model.ScriptOptionsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ScriptOptions service. Represents a row in the &quot;scriptpp_ScriptOptions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link hu.borkuti.peter.scriptpp.service.model.ScriptOptionsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScriptOptionsImpl}.
 * </p>
 *
 * @author Peter Borkuti
 * @see ScriptOptionsImpl
 * @see hu.borkuti.peter.scriptpp.service.model.ScriptOptions
 * @see hu.borkuti.peter.scriptpp.service.model.ScriptOptionsModel
 * @generated
 */
@JSON(strict = true)
public class ScriptOptionsModelImpl extends BaseModelImpl<ScriptOptions>
	implements ScriptOptionsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a script options model instance should use the {@link hu.borkuti.peter.scriptpp.service.model.ScriptOptions} interface instead.
	 */
	public static final String TABLE_NAME = "scriptpp_ScriptOptions";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ScriptOptionsId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "scriptName", Types.VARCHAR },
			{ "dependencyList", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table scriptpp_ScriptOptions (ScriptOptionsId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,scriptName VARCHAR(75) null,dependencyList VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table scriptpp_ScriptOptions";
	public static final String ORDER_BY_JPQL = " ORDER BY scriptOptions.scriptName DESC, scriptOptions.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY scriptpp_ScriptOptions.scriptName DESC, scriptpp_ScriptOptions.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.hu.borkuti.peter.scriptpp.service.model.ScriptOptions"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.hu.borkuti.peter.scriptpp.service.model.ScriptOptions"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.hu.borkuti.peter.scriptpp.service.model.ScriptOptions"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long SCRIPTNAME_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ScriptOptions toModel(ScriptOptionsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ScriptOptions model = new ScriptOptionsImpl();

		model.setScriptOptionsId(soapModel.getScriptOptionsId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setScriptName(soapModel.getScriptName());
		model.setDependencyList(soapModel.getDependencyList());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ScriptOptions> toModels(ScriptOptionsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ScriptOptions> models = new ArrayList<ScriptOptions>(soapModels.length);

		for (ScriptOptionsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.hu.borkuti.peter.scriptpp.service.model.ScriptOptions"));

	public ScriptOptionsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ScriptOptionsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScriptOptionsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ScriptOptionsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScriptOptions.class;
	}

	@Override
	public String getModelClassName() {
		return ScriptOptions.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ScriptOptionsId", getScriptOptionsId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("scriptName", getScriptName());
		attributes.put("dependencyList", getDependencyList());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ScriptOptionsId = (Long)attributes.get("ScriptOptionsId");

		if (ScriptOptionsId != null) {
			setScriptOptionsId(ScriptOptionsId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String scriptName = (String)attributes.get("scriptName");

		if (scriptName != null) {
			setScriptName(scriptName);
		}

		String dependencyList = (String)attributes.get("dependencyList");

		if (dependencyList != null) {
			setDependencyList(dependencyList);
		}
	}

	@JSON
	@Override
	public long getScriptOptionsId() {
		return _ScriptOptionsId;
	}

	@Override
	public void setScriptOptionsId(long ScriptOptionsId) {
		_ScriptOptionsId = ScriptOptionsId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getScriptName() {
		if (_scriptName == null) {
			return StringPool.BLANK;
		}
		else {
			return _scriptName;
		}
	}

	@Override
	public void setScriptName(String scriptName) {
		_columnBitmask = -1L;

		if (_originalScriptName == null) {
			_originalScriptName = _scriptName;
		}

		_scriptName = scriptName;
	}

	public String getOriginalScriptName() {
		return GetterUtil.getString(_originalScriptName);
	}

	@JSON
	@Override
	public String getDependencyList() {
		if (_dependencyList == null) {
			return StringPool.BLANK;
		}
		else {
			return _dependencyList;
		}
	}

	@Override
	public void setDependencyList(String dependencyList) {
		_dependencyList = dependencyList;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ScriptOptions.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScriptOptions toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ScriptOptions)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScriptOptionsImpl scriptOptionsImpl = new ScriptOptionsImpl();

		scriptOptionsImpl.setScriptOptionsId(getScriptOptionsId());
		scriptOptionsImpl.setCompanyId(getCompanyId());
		scriptOptionsImpl.setGroupId(getGroupId());
		scriptOptionsImpl.setUserId(getUserId());
		scriptOptionsImpl.setCreateDate(getCreateDate());
		scriptOptionsImpl.setModifiedDate(getModifiedDate());
		scriptOptionsImpl.setScriptName(getScriptName());
		scriptOptionsImpl.setDependencyList(getDependencyList());

		scriptOptionsImpl.resetOriginalValues();

		return scriptOptionsImpl;
	}

	@Override
	public int compareTo(ScriptOptions scriptOptions) {
		int value = 0;

		value = getScriptName().compareTo(scriptOptions.getScriptName());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(),
				scriptOptions.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScriptOptions)) {
			return false;
		}

		ScriptOptions scriptOptions = (ScriptOptions)obj;

		long primaryKey = scriptOptions.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ScriptOptionsModelImpl scriptOptionsModelImpl = this;

		scriptOptionsModelImpl._originalGroupId = scriptOptionsModelImpl._groupId;

		scriptOptionsModelImpl._setOriginalGroupId = false;

		scriptOptionsModelImpl._originalUserId = scriptOptionsModelImpl._userId;

		scriptOptionsModelImpl._setOriginalUserId = false;

		scriptOptionsModelImpl._originalScriptName = scriptOptionsModelImpl._scriptName;

		scriptOptionsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ScriptOptions> toCacheModel() {
		ScriptOptionsCacheModel scriptOptionsCacheModel = new ScriptOptionsCacheModel();

		scriptOptionsCacheModel.ScriptOptionsId = getScriptOptionsId();

		scriptOptionsCacheModel.companyId = getCompanyId();

		scriptOptionsCacheModel.groupId = getGroupId();

		scriptOptionsCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			scriptOptionsCacheModel.createDate = createDate.getTime();
		}
		else {
			scriptOptionsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			scriptOptionsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			scriptOptionsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		scriptOptionsCacheModel.scriptName = getScriptName();

		String scriptName = scriptOptionsCacheModel.scriptName;

		if ((scriptName != null) && (scriptName.length() == 0)) {
			scriptOptionsCacheModel.scriptName = null;
		}

		scriptOptionsCacheModel.dependencyList = getDependencyList();

		String dependencyList = scriptOptionsCacheModel.dependencyList;

		if ((dependencyList != null) && (dependencyList.length() == 0)) {
			scriptOptionsCacheModel.dependencyList = null;
		}

		return scriptOptionsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{ScriptOptionsId=");
		sb.append(getScriptOptionsId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", scriptName=");
		sb.append(getScriptName());
		sb.append(", dependencyList=");
		sb.append(getDependencyList());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("hu.borkuti.peter.scriptpp.service.model.ScriptOptions");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ScriptOptionsId</column-name><column-value><![CDATA[");
		sb.append(getScriptOptionsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scriptName</column-name><column-value><![CDATA[");
		sb.append(getScriptName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dependencyList</column-name><column-value><![CDATA[");
		sb.append(getDependencyList());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ScriptOptions.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ScriptOptions.class
		};
	private long _ScriptOptionsId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _scriptName;
	private String _originalScriptName;
	private String _dependencyList;
	private long _columnBitmask;
	private ScriptOptions _escapedModel;
}