/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.borkuti.peter.scriptpp.service.model.impl;

import hu.borkuti.peter.scriptpp.service.model.ScriptOptions;

/**
 * The extended model base implementation for the ScriptOptions service. Represents a row in the &quot;scriptpp_ScriptOptions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScriptOptionsImpl}.
 * </p>
 *
 * @author Peter Borkuti
 * @see ScriptOptionsImpl
 * @see hu.borkuti.peter.scriptpp.service.model.ScriptOptions
 * @generated
 */
public abstract class ScriptOptionsBaseImpl extends ScriptOptionsModelImpl
	implements ScriptOptions {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a script options model instance should use the {@link ScriptOptions} interface instead.
	 */
}