/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package permission.servicebuider.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import permission.servicebuider.model.Firstnames;

import permission.servicebuider.service.FirstnamesLocalServiceUtil;

/**
 * The extended model base implementation for the Firstnames service. Represents a row in the &quot;permissiontest_Firstnames&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FirstnamesImpl}.
 * </p>
 *
 * @author peter
 * @see FirstnamesImpl
 * @see permission.servicebuider.model.Firstnames
 * @generated
 */
public abstract class FirstnamesBaseImpl extends FirstnamesModelImpl
	implements Firstnames {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a firstnames model instance should use the {@link Firstnames} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FirstnamesLocalServiceUtil.addFirstnames(this);
		}
		else {
			FirstnamesLocalServiceUtil.updateFirstnames(this);
		}
	}
}