/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package permission.servicebuider.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import permission.servicebuider.model.Firstnames;
import permission.servicebuider.model.FirstnamesModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Firstnames service. Represents a row in the &quot;permissiontest_Firstnames&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link permission.servicebuider.model.FirstnamesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FirstnamesImpl}.
 * </p>
 *
 * @author peter
 * @see FirstnamesImpl
 * @see permission.servicebuider.model.Firstnames
 * @see permission.servicebuider.model.FirstnamesModel
 * @generated
 */
public class FirstnamesModelImpl extends BaseModelImpl<Firstnames>
	implements FirstnamesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a firstnames model instance should use the {@link permission.servicebuider.model.Firstnames} interface instead.
	 */
	public static final String TABLE_NAME = "permissiontest_Firstnames";
	public static final Object[][] TABLE_COLUMNS = {
			{ "firstnameId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "firstname", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table permissiontest_Firstnames (firstnameId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,firstname VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table permissiontest_Firstnames";
	public static final String ORDER_BY_JPQL = " ORDER BY firstnames.firstname ASC";
	public static final String ORDER_BY_SQL = " ORDER BY permissiontest_Firstnames.firstname ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.permission.servicebuider.model.Firstnames"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.permission.servicebuider.model.Firstnames"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.permission.servicebuider.model.Firstnames"),
			true);
	public static long FIRSTNAME_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.permission.servicebuider.model.Firstnames"));

	public FirstnamesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _firstnameId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFirstnameId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _firstnameId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Firstnames.class;
	}

	@Override
	public String getModelClassName() {
		return Firstnames.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("firstnameId", getFirstnameId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("firstname", getFirstname());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long firstnameId = (Long)attributes.get("firstnameId");

		if (firstnameId != null) {
			setFirstnameId(firstnameId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String firstname = (String)attributes.get("firstname");

		if (firstname != null) {
			setFirstname(firstname);
		}
	}

	@Override
	public long getFirstnameId() {
		return _firstnameId;
	}

	@Override
	public void setFirstnameId(long firstnameId) {
		_firstnameId = firstnameId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFirstname() {
		if (_firstname == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstname;
		}
	}

	@Override
	public void setFirstname(String firstname) {
		_columnBitmask = -1L;

		if (_originalFirstname == null) {
			_originalFirstname = _firstname;
		}

		_firstname = firstname;
	}

	public String getOriginalFirstname() {
		return GetterUtil.getString(_originalFirstname);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Firstnames.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Firstnames toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Firstnames)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FirstnamesImpl firstnamesImpl = new FirstnamesImpl();

		firstnamesImpl.setFirstnameId(getFirstnameId());
		firstnamesImpl.setGroupId(getGroupId());
		firstnamesImpl.setCompanyId(getCompanyId());
		firstnamesImpl.setUserId(getUserId());
		firstnamesImpl.setCreateDate(getCreateDate());
		firstnamesImpl.setModifiedDate(getModifiedDate());
		firstnamesImpl.setFirstname(getFirstname());

		firstnamesImpl.resetOriginalValues();

		return firstnamesImpl;
	}

	@Override
	public int compareTo(Firstnames firstnames) {
		int value = 0;

		value = getFirstname().compareTo(firstnames.getFirstname());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Firstnames)) {
			return false;
		}

		Firstnames firstnames = (Firstnames)obj;

		long primaryKey = firstnames.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FirstnamesModelImpl firstnamesModelImpl = this;

		firstnamesModelImpl._originalFirstname = firstnamesModelImpl._firstname;

		firstnamesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Firstnames> toCacheModel() {
		FirstnamesCacheModel firstnamesCacheModel = new FirstnamesCacheModel();

		firstnamesCacheModel.firstnameId = getFirstnameId();

		firstnamesCacheModel.groupId = getGroupId();

		firstnamesCacheModel.companyId = getCompanyId();

		firstnamesCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			firstnamesCacheModel.createDate = createDate.getTime();
		}
		else {
			firstnamesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			firstnamesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			firstnamesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		firstnamesCacheModel.firstname = getFirstname();

		String firstname = firstnamesCacheModel.firstname;

		if ((firstname != null) && (firstname.length() == 0)) {
			firstnamesCacheModel.firstname = null;
		}

		return firstnamesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{firstnameId=");
		sb.append(getFirstnameId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", firstname=");
		sb.append(getFirstname());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("permission.servicebuider.model.Firstnames");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>firstnameId</column-name><column-value><![CDATA[");
		sb.append(getFirstnameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstname</column-name><column-value><![CDATA[");
		sb.append(getFirstname());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Firstnames.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Firstnames.class
		};
	private long _firstnameId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _firstname;
	private String _originalFirstname;
	private long _columnBitmask;
	private Firstnames _escapedModel;
}